export const GITHUB_REPO = 'https://github.com/jontonsoup4/suno-clone';

export const USER = {
  id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
  username: 'jontonsoup',
  credits: 550,
};

export const MODELS = [
  {
    external_key: 'chirp-v3-0',
    id: '3.0.0',
    major_version: 3,
    name: 'v3',
  },
  {
    external_key: 'chirp-v2-0',
    id: '2.0.0',
    major_version: 2,
    name: 'v2',
  },
];

export const SONGS = [
  {
    id: '5dbf6600-21cf-4cd8-a8b1-a95300293a0b',
    video_url: 'https://cdn1.suno.ai/5dbf6600-21cf-4cd8-a8b1-a95300293a0b.mp4',
    audio_url: 'https://cdn1.suno.ai/5dbf6600-21cf-4cd8-a8b1-a95300293a0b.mp3',
    image_url: 'https://cdn1.suno.ai/image_5dbf6600-21cf-4cd8-a8b1-a95300293a0b.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_5dbf6600-21cf-4cd8-a8b1-a95300293a0b.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'haunting electronic dark',
      prompt:
        "[Verse]\nIn the shadows of this empty room\nWhere your presence used to be my light\nNow it's darkness that consumes\nEvery corner\nEvery inch of my mind\n\nIn the silence\nI hear your ghost\nEchoes in the walls\nA haunting sound\nWhispers of love that I miss the most\nBut now you're gone\nNowhere to be found\n\n[Verse 2]\nThe floors creak under my heavy steps\nA reminder of the life we once shared\nBut now all that remains are regrets\nAching heart\nFeeling so unprepared",
      gpt_description_prompt: "a dark house song about when you're not around",
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 115.0,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: false,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: null,
    created_at: '2024-05-06T18:38:55.622Z',
    status: 'complete',
    title: "When You're Gone",
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '45bee510-0dda-43d6-8590-5a606318595f',
    video_url: 'https://cdn1.suno.ai/45bee510-0dda-43d6-8590-5a606318595f.mp4',
    audio_url: 'https://cdn1.suno.ai/45bee510-0dda-43d6-8590-5a606318595f.mp3',
    image_url: 'https://cdn1.suno.ai/image_45bee510-0dda-43d6-8590-5a606318595f.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_45bee510-0dda-43d6-8590-5a606318595f.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'haunting electronic dark',
      prompt:
        "[Verse]\nIn the shadows of this empty room\nWhere your presence used to be my light\nNow it's darkness that consumes\nEvery corner\nEvery inch of my mind\n\nIn the silence\nI hear your ghost\nEchoes in the walls\nA haunting sound\nWhispers of love that I miss the most\nBut now you're gone\nNowhere to be found\n\n[Verse 2]\nThe floors creak under my heavy steps\nA reminder of the life we once shared\nBut now all that remains are regrets\nAching heart\nFeeling so unprepared",
      gpt_description_prompt: "a dark house song about when you're not around",
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 100.96,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: false,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: null,
    created_at: '2024-05-06T18:38:55.622Z',
    status: 'complete',
    title: "When You're Gone",
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '61a6ab3b-2eb2-46f3-b796-4200c7a44a1a',
    video_url: 'https://cdn1.suno.ai/61a6ab3b-2eb2-46f3-b796-4200c7a44a1a.mp4',
    audio_url: 'https://cdn1.suno.ai/61a6ab3b-2eb2-46f3-b796-4200c7a44a1a.mp3',
    image_url: 'https://cdn1.suno.ai/image_61a6ab3b-2eb2-46f3-b796-4200c7a44a1a.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_61a6ab3b-2eb2-46f3-b796-4200c7a44a1a.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'emotional edm',
      prompt:
        "(Verse 1)\nWe're a team in Cambridge, MA,\nWith Meta, TikTok, Kensho in our DNA.\nCoding, making music, sippin' on that brew,\nIn our Suno groove, we're breaking through.\n\n(Chorus)\nWe're Suno, yeah, that's who we are,\nMixing tech and tunes, reaching for the stars.\nFrom the office to the stage, we're living our dream,\nCome join our team, let's make it gleam.\n\n(Verse 2)\nFrom lunchroom chats to the studio light,\nInnovation's our jam, we're taking flight.\nWith beats in our hearts and algorithms in our brain,\nSuno's where music and tech reign.\n\n(Chorus)\nWe're Suno, yeah, that's who we are,\nMixing tech and tunes, reaching for the stars.\nFrom the office to the stage, we're living our dream,\nCome join our team, let's make it gleam.",
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 120.0,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '61a6ab3b-2eb2-46f3-b796-4200c7a44a1a',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-24T06:14:08.028Z',
    },
    created_at: '2024-04-24T06:11:59.987Z',
    status: 'complete',
    title: 'Join Suno',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '28b87474-af75-46e1-9f70-104cf624ceb2',
    video_url: 'https://cdn1.suno.ai/28b87474-af75-46e1-9f70-104cf624ceb2.mp4',
    audio_url: 'https://cdn1.suno.ai/28b87474-af75-46e1-9f70-104cf624ceb2.mp3',
    image_url: 'https://cdn1.suno.ai/image_28b87474-af75-46e1-9f70-104cf624ceb2.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_28b87474-af75-46e1-9f70-104cf624ceb2.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'emotional edm',
      prompt:
        "(Verse 1)\nWe're a team in Cambridge, MA,\nWith Meta, TikTok, Kensho in our DNA.\nCoding, making music, sippin' on that brew,\nIn our Suno groove, we're breaking through.\n\n(Chorus)\nWe're Suno, yeah, that's who we are,\nMixing tech and tunes, reaching for the stars.\nFrom the office to the stage, we're living our dream,\nCome join our team, let's make it gleam.\n\n(Verse 2)\nFrom lunchroom chats to the studio light,\nInnovation's our jam, we're taking flight.\nWith beats in our hearts and algorithms in our brain,\nSuno's where music and tech reign.\n\n(Chorus)\nWe're Suno, yeah, that's who we are,\nMixing tech and tunes, reaching for the stars.\nFrom the office to the stage, we're living our dream,\nCome join our team, let's make it gleam.",
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 75.2,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '28b87474-af75-46e1-9f70-104cf624ceb2',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-24T06:12:52.562Z',
    },
    created_at: '2024-04-24T06:11:59.987Z',
    status: 'complete',
    title: 'Join Suno',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: 'e43d450b-0abf-4a11-a874-6ed9877e56e2',
    video_url: 'https://cdn1.suno.ai/e43d450b-0abf-4a11-a874-6ed9877e56e2.mp4',
    audio_url: 'https://cdn1.suno.ai/e43d450b-0abf-4a11-a874-6ed9877e56e2.mp3',
    image_url: 'https://cdn1.suno.ai/image_e43d450b-0abf-4a11-a874-6ed9877e56e2.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_e43d450b-0abf-4a11-a874-6ed9877e56e2.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'emotional edm',
      prompt:
        "[Verse]\nWe are a team of musicians and artificial intelligence experts based in Cambridge, MA. \nWe are proud alumni of pioneering tech companies like Meta, TikTok and Kensho, where our founding team worked together before starting Suno.\n\n[Chorus]\nWe like to ship code, \nWe like to make music\nWe like to drink coffee. \n\n[Drop]\n\n[Verse]\nOur company culture is all about music and experimenting with sound\nFrom lunchroom conversations to the studio in our office. \nIf you're any of these things or nothing of the sort, we'd love to hear from you.\n\n[Chorus]\nWe like to ship code, \nWe like to make music\nWe like to drink coffee. \n\n[Drop]",
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 120.0,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: 'e43d450b-0abf-4a11-a874-6ed9877e56e2',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-24T06:08:40.515Z',
    },
    created_at: '2024-04-24T06:06:48.014Z',
    status: 'complete',
    title: 'Suno',
    play_count: 8,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '8ab07f97-0d1a-4f1e-ba0c-7d01facd74eb',
    video_url: 'https://cdn1.suno.ai/8ab07f97-0d1a-4f1e-ba0c-7d01facd74eb.mp4',
    audio_url: 'https://cdn1.suno.ai/8ab07f97-0d1a-4f1e-ba0c-7d01facd74eb.mp3',
    image_url: 'https://cdn1.suno.ai/image_8ab07f97-0d1a-4f1e-ba0c-7d01facd74eb.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_8ab07f97-0d1a-4f1e-ba0c-7d01facd74eb.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'emotional edm',
      prompt:
        "[Verse]\nWe are a team of musicians and artificial intelligence experts based in Cambridge, MA. \nWe are proud alumni of pioneering tech companies like Meta, TikTok and Kensho, where our founding team worked together before starting Suno.\n\n[Chorus]\nWe like to ship code, \nWe like to make music\nWe like to drink coffee. \n\n[Drop]\n\n[Verse]\nOur company culture is all about music and experimenting with sound\nFrom lunchroom conversations to the studio in our office. \nIf you're any of these things or nothing of the sort, we'd love to hear from you.\n\n[Chorus]\nWe like to ship code, \nWe like to make music\nWe like to drink coffee. \n\n[Drop]",
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 73.56,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '8ab07f97-0d1a-4f1e-ba0c-7d01facd74eb',
      play_count: 2,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-24T06:07:52.803Z',
    },
    created_at: '2024-04-24T06:06:48.014Z',
    status: 'complete',
    title: 'Suno',
    play_count: 10,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: 'fa8f8ecf-5937-4e1a-8f70-45bf0cae3551',
    video_url: 'https://cdn1.suno.ai/fa8f8ecf-5937-4e1a-8f70-45bf0cae3551.mp4',
    audio_url: 'https://cdn1.suno.ai/fa8f8ecf-5937-4e1a-8f70-45bf0cae3551.mp3',
    image_url: 'https://cdn1.suno.ai/image_fa8f8ecf-5937-4e1a-8f70-45bf0cae3551.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_fa8f8ecf-5937-4e1a-8f70-45bf0cae3551.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'comedic musical theatre',
      prompt:
        "[Verse 1]\nIn a world consumed by macaroni and cheese\nOne food stands out\nBringin' folks to their knees\nBoil 'em up\nSeason 'em right\nMake 'em your own\nBut beware\nMy friend\nOf the beans that are sown\n\n[Verse 2]\nOh\nThe Baked Beans of Destruction\nThey're a force to behold\nWith their gassy power\nThey can't be controlled\nOne bite and you're done\nIt's a culinary fight\nBut we can't resist the flavor\nNo matter how it might ignite\n\n[Chorus]\nBaked Beans of Destruction\nThey're a gas-filled delight\nThey'll make you laugh\nCry\nAnd keep you up all night\nBut take caution\nMy friend\nWhen you lift that lid\nFor the Baked Beans of Destruction\nThey'll blow you to bits (oh-oh)",
      gpt_description_prompt: 'a musical theatre song about baked beans of destruction',
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 88.0,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: 'fa8f8ecf-5937-4e1a-8f70-45bf0cae3551',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-14T10:55:46.636Z',
    },
    created_at: '2024-04-14T10:52:49.412Z',
    status: 'complete',
    title: 'The Baked Beans Ballad',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '3b47646c-facb-42ae-aac8-0ae98a136b93',
    video_url: 'https://cdn1.suno.ai/3b47646c-facb-42ae-aac8-0ae98a136b93.mp4',
    audio_url: 'https://cdn1.suno.ai/3b47646c-facb-42ae-aac8-0ae98a136b93.mp3',
    image_url: 'https://cdn1.suno.ai/image_3b47646c-facb-42ae-aac8-0ae98a136b93.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_3b47646c-facb-42ae-aac8-0ae98a136b93.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'comedic musical theatre',
      prompt:
        "[Verse 1]\nIn a world consumed by macaroni and cheese\nOne food stands out\nBringin' folks to their knees\nBoil 'em up\nSeason 'em right\nMake 'em your own\nBut beware\nMy friend\nOf the beans that are sown\n\n[Verse 2]\nOh\nThe Baked Beans of Destruction\nThey're a force to behold\nWith their gassy power\nThey can't be controlled\nOne bite and you're done\nIt's a culinary fight\nBut we can't resist the flavor\nNo matter how it might ignite\n\n[Chorus]\nBaked Beans of Destruction\nThey're a gas-filled delight\nThey'll make you laugh\nCry\nAnd keep you up all night\nBut take caution\nMy friend\nWhen you lift that lid\nFor the Baked Beans of Destruction\nThey'll blow you to bits (oh-oh)",
      gpt_description_prompt: 'a musical theatre song about baked beans of destruction',
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 68.0,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '3b47646c-facb-42ae-aac8-0ae98a136b93',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-14T10:54:38.012Z',
    },
    created_at: '2024-04-14T10:52:49.412Z',
    status: 'complete',
    title: 'The Baked Beans Ballad',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: 'e90a289b-a695-40f7-b4f0-75b7d452637f',
    video_url: 'https://cdn1.suno.ai/e90a289b-a695-40f7-b4f0-75b7d452637f.mp4',
    audio_url: 'https://cdn1.suno.ai/e90a289b-a695-40f7-b4f0-75b7d452637f.mp3',
    image_url: 'https://cdn1.suno.ai/image_e90a289b-a695-40f7-b4f0-75b7d452637f.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_e90a289b-a695-40f7-b4f0-75b7d452637f.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'comedic musical theater',
      prompt:
        "[Verse 1: Baker]\nIn a world of sugar and cream\nThere's a treat that makes us beam\nWith a texture smooth and sweet\nPudding's what we can't defeat\n\n[Verse 1: Baker's Assistant]\nAdded sugar\nEggs\nAnd milk\nStir it up\nJust like silk\nButterscotch\nChocolate\nOr vanilla\nIn our bowls\nIt's a thrill-a!\n\n[Chorus: Both]\nOh\nPudding\nYou're the star of the night\nA delightful dream\nA sugary delight\nLet's scoop it up and savor each bite\nPudding\nOur forever favorite dessert!",
      gpt_description_prompt: 'a musical theater duet about pudding',
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 77.0,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: 'e90a289b-a695-40f7-b4f0-75b7d452637f',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-14T10:53:20.331Z',
    },
    created_at: '2024-04-14T10:50:13.507Z',
    status: 'complete',
    title: 'Sweet Delights',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '4f85ba33-bfd9-4b08-aecd-ab1822b59e49',
    video_url: 'https://cdn1.suno.ai/4f85ba33-bfd9-4b08-aecd-ab1822b59e49.mp4',
    audio_url: 'https://cdn1.suno.ai/4f85ba33-bfd9-4b08-aecd-ab1822b59e49.mp3',
    image_url: 'https://cdn1.suno.ai/image_4f85ba33-bfd9-4b08-aecd-ab1822b59e49.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_4f85ba33-bfd9-4b08-aecd-ab1822b59e49.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'comedic musical theater',
      prompt:
        "[Verse 1: Baker]\nIn a world of sugar and cream\nThere's a treat that makes us beam\nWith a texture smooth and sweet\nPudding's what we can't defeat\n\n[Verse 1: Baker's Assistant]\nAdded sugar\nEggs\nAnd milk\nStir it up\nJust like silk\nButterscotch\nChocolate\nOr vanilla\nIn our bowls\nIt's a thrill-a!\n\n[Chorus: Both]\nOh\nPudding\nYou're the star of the night\nA delightful dream\nA sugary delight\nLet's scoop it up and savor each bite\nPudding\nOur forever favorite dessert!",
      gpt_description_prompt: 'a musical theater duet about pudding',
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 84.96,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '4f85ba33-bfd9-4b08-aecd-ab1822b59e49',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-14T10:51:54.590Z',
    },
    created_at: '2024-04-14T10:50:13.507Z',
    status: 'complete',
    title: 'Sweet Delights',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '8cbbfecb-8222-4ade-b0b7-f142ed05ee92',
    video_url: 'https://cdn1.suno.ai/8cbbfecb-8222-4ade-b0b7-f142ed05ee92.mp4',
    audio_url: 'https://cdn1.suno.ai/8cbbfecb-8222-4ade-b0b7-f142ed05ee92.mp3',
    image_url: 'https://cdn1.suno.ai/image_8cbbfecb-8222-4ade-b0b7-f142ed05ee92.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_8cbbfecb-8222-4ade-b0b7-f142ed05ee92.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'rock punk alternative',
      prompt:
        "[Verse 1]\nI'm a full-time ragdoll\nA part-time snowboarder\nShreddin' the slopes\nCatchin' air as I go (whoa-oh)\nBeneath the neon lights\nI'm a digital intellect\nMatching skills with a slippery board\nWhat a perfect disconnect\n\n[Verse 2]\nI carve through the chaos\nDefying gravity's call\nAs the world spins around\nI'm ready to take the fall (fall)\nDodging glitches in the matrix\nA rebel in the code\nRiding the pixelated waves\nMy spirit fully bestowed\n\n[Chorus]\nDigital intellect versus slippery board (whoa-oh)\nIn this virtual realm\nI find my reward (yeah-eah)\nI glitch through the barriers\nBreak the status quo (whoa-oh)\nA punk on the slopes\nWhere my spirit will glow (yeah-eah, oh-oh)",
      gpt_description_prompt:
        'full time ragdoll, extreme part time snowboarder, professional snow muncher, digital intellect versus slippery board',
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 93.0,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '8cbbfecb-8222-4ade-b0b7-f142ed05ee92',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-14T10:49:53.861Z',
    },
    created_at: '2024-04-14T10:25:42.821Z',
    status: 'complete',
    title: 'Digital Glitch',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '547a2d21-9a74-4a6c-8006-25281678cf68',
    video_url: 'https://cdn1.suno.ai/547a2d21-9a74-4a6c-8006-25281678cf68.mp4',
    audio_url: 'https://cdn1.suno.ai/547a2d21-9a74-4a6c-8006-25281678cf68.mp3',
    image_url: 'https://cdn1.suno.ai/image_547a2d21-9a74-4a6c-8006-25281678cf68.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_547a2d21-9a74-4a6c-8006-25281678cf68.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'rock punk alternative',
      prompt:
        "[Verse 1]\nI'm a full-time ragdoll\nA part-time snowboarder\nShreddin' the slopes\nCatchin' air as I go (whoa-oh)\nBeneath the neon lights\nI'm a digital intellect\nMatching skills with a slippery board\nWhat a perfect disconnect\n\n[Verse 2]\nI carve through the chaos\nDefying gravity's call\nAs the world spins around\nI'm ready to take the fall (fall)\nDodging glitches in the matrix\nA rebel in the code\nRiding the pixelated waves\nMy spirit fully bestowed\n\n[Chorus]\nDigital intellect versus slippery board (whoa-oh)\nIn this virtual realm\nI find my reward (yeah-eah)\nI glitch through the barriers\nBreak the status quo (whoa-oh)\nA punk on the slopes\nWhere my spirit will glow (yeah-eah, oh-oh)",
      gpt_description_prompt:
        'full time ragdoll, extreme part time snowboarder, professional snow muncher, digital intellect versus slippery board',
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 92.8,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '547a2d21-9a74-4a6c-8006-25281678cf68',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-14T10:48:39.138Z',
    },
    created_at: '2024-04-14T10:25:42.820Z',
    status: 'complete',
    title: 'Digital Glitch',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: 'f5c634f3-c758-41dc-abb3-1490fcb48de2',
    video_url: 'https://cdn1.suno.ai/f5c634f3-c758-41dc-abb3-1490fcb48de2.mp4',
    audio_url: 'https://cdn1.suno.ai/f5c634f3-c758-41dc-abb3-1490fcb48de2.mp3',
    image_url: 'https://cdn1.suno.ai/image_f5c634f3-c758-41dc-abb3-1490fcb48de2.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_f5c634f3-c758-41dc-abb3-1490fcb48de2.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'futuristic kids music',
      prompt:
        '[Verse]\nMan\nBoy\nMan\nBoy\n\n[Prechorus]\nMan boy\nBoy man\nMan boy\nBoy man\n\n[Chorus]\nMan boy, man boy\nMan boy, man boy\nMan boy, man boy\nMan boy, man boy\n\n[Verse]\nMan\nBoy\nMan\nBoy\n\n[Prechorus]\nMan boy\nBoy man\nMan boy\nBoy man\n\n[Chorus]\nMan boy, man boy\nMan boy, man boy\nMan boy, man boy\nMan boy, man boy',
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 120.0,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: 'f5c634f3-c758-41dc-abb3-1490fcb48de2',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-13T08:37:40.591Z',
    },
    created_at: '2024-04-13T08:25:10.233Z',
    status: 'complete',
    title: 'Man Boy',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: 'eb14b7cb-f2b7-46dd-8939-fa008f222fb3',
    video_url: 'https://cdn1.suno.ai/eb14b7cb-f2b7-46dd-8939-fa008f222fb3.mp4',
    audio_url: 'https://cdn1.suno.ai/eb14b7cb-f2b7-46dd-8939-fa008f222fb3.mp3',
    image_url: 'https://cdn1.suno.ai/image_eb14b7cb-f2b7-46dd-8939-fa008f222fb3.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_eb14b7cb-f2b7-46dd-8939-fa008f222fb3.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'futuristic kids music',
      prompt:
        '[Verse]\nMan\nBoy\nMan\nBoy\n\n[Prechorus]\nMan boy\nBoy man\nMan boy\nBoy man\n\n[Chorus]\nMan boy, man boy\nMan boy, man boy\nMan boy, man boy\nMan boy, man boy\n\n[Verse]\nMan\nBoy\nMan\nBoy\n\n[Prechorus]\nMan boy\nBoy man\nMan boy\nBoy man\n\n[Chorus]\nMan boy, man boy\nMan boy, man boy\nMan boy, man boy\nMan boy, man boy',
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 118.4,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: 'eb14b7cb-f2b7-46dd-8939-fa008f222fb3',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-13T08:37:12.337Z',
    },
    created_at: '2024-04-13T08:25:10.233Z',
    status: 'complete',
    title: 'Man Boy',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: 'cdf1eaaa-3a0a-4a5f-b05d-df35d9aa0bf5',
    video_url: 'https://cdn1.suno.ai/cdf1eaaa-3a0a-4a5f-b05d-df35d9aa0bf5.mp4',
    audio_url: 'https://cdn1.suno.ai/cdf1eaaa-3a0a-4a5f-b05d-df35d9aa0bf5.mp3',
    image_url: 'https://cdn1.suno.ai/image_cdf1eaaa-3a0a-4a5f-b05d-df35d9aa0bf5.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_cdf1eaaa-3a0a-4a5f-b05d-df35d9aa0bf5.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'futuristic kids music',
      prompt:
        "[Verse 1]\nEvery day feels like a brand new start (ooh-yeah)\nWalking on sunshine with an open heart\nNo more rainy days\nThey're a thing of the past\nGot a smile on my face that's bound to last (oh-oh)\n\n[Chorus]\nSunshine and rainbows\nI'm catchin' the glow (oh-oh)\nDancing through life\nNo more feeling low (feeling low)\nEvery step I take\nThe world's spinning around\nSo much more to see\nSo much love to be found\n\n[Verse 2]\nUsed to be caught up in a stormy haze (ooh-yeah)\nDark clouds followin' me\nEndless maze\nBut now I've found my way to brighter skies\nUnleashing all the colors\nLet 'em mesmerize (oh-oh)\n\n[Chorus]\nSunshine and rainbows\nI'm catchin' the glow (oh-oh)\nDancing through life\nNo more feeling low (feeling low)\nEvery step I take\nThe world's spinning around\nSo much more to see\nSo much love to be found",
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 100.8,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: 'cdf1eaaa-3a0a-4a5f-b05d-df35d9aa0bf5',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-13T07:44:52.601Z',
    },
    created_at: '2024-04-13T07:40:32.190Z',
    status: 'complete',
    title: 'Sunshine and Rainbows',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: 'aafb02cc-19aa-4146-b048-8e616b666318',
    video_url: 'https://cdn1.suno.ai/aafb02cc-19aa-4146-b048-8e616b666318.mp4',
    audio_url: 'https://cdn1.suno.ai/aafb02cc-19aa-4146-b048-8e616b666318.mp3',
    image_url: 'https://cdn1.suno.ai/image_aafb02cc-19aa-4146-b048-8e616b666318.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_aafb02cc-19aa-4146-b048-8e616b666318.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'futuristic kids music',
      prompt:
        "[Verse 1]\nEvery day feels like a brand new start (ooh-yeah)\nWalking on sunshine with an open heart\nNo more rainy days\nThey're a thing of the past\nGot a smile on my face that's bound to last (oh-oh)\n\n[Chorus]\nSunshine and rainbows\nI'm catchin' the glow (oh-oh)\nDancing through life\nNo more feeling low (feeling low)\nEvery step I take\nThe world's spinning around\nSo much more to see\nSo much love to be found\n\n[Verse 2]\nUsed to be caught up in a stormy haze (ooh-yeah)\nDark clouds followin' me\nEndless maze\nBut now I've found my way to brighter skies\nUnleashing all the colors\nLet 'em mesmerize (oh-oh)\n\n[Chorus]\nSunshine and rainbows\nI'm catchin' the glow (oh-oh)\nDancing through life\nNo more feeling low (feeling low)\nEvery step I take\nThe world's spinning around\nSo much more to see\nSo much love to be found",
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 107.44,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: 'aafb02cc-19aa-4146-b048-8e616b666318',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-13T07:43:47.460Z',
    },
    created_at: '2024-04-13T07:40:32.190Z',
    status: 'complete',
    title: 'Sunshine and Rainbows',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: 'f959f758-561d-4aa6-9c56-680ef3b03b15',
    video_url: 'https://cdn1.suno.ai/f959f758-561d-4aa6-9c56-680ef3b03b15.mp4',
    audio_url: 'https://cdn1.suno.ai/f959f758-561d-4aa6-9c56-680ef3b03b15.mp3',
    image_url: 'https://cdn1.suno.ai/image_62e9a150-c8d4-4d0f-a192-de69094d7faa.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_62e9a150-c8d4-4d0f-a192-de69094d7faa.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'uplifting bluegrass',
      prompt:
        "[Verse 1]\nIn fields where wild winds dance and play,\nWhere sunbeams paint the dawning day,\nThere strides a friend, both swift and true,\nAcross the fields, beneath skies so blue,\n\n[Pre-chorus]\nWith mane that flows like rivers free,\nAnd eyes that hold eternity,\nEach hoofbeat echoes tales untold,\nOf journeys vast and dreams unfold.\n\n[Chorus]\nMay the horse be with you\nMay the horse be with you\nIn every gallop, every stride\nMay the horse be with you\n\n[Verse 2]\nThrough meadows green and valleys deep,\nWith May, the horse, there's naught to keep,\nBut soaring hearts and spirits bright,\nGuided by the stars at night.\n\n[Pre-chorus]\nWith mane that flows like rivers free,\nAnd eyes that hold eternity,\nEach hoofbeat echoes tales untold,\nOf journeys vast and dreams unfold.\n\n[Chorus]\nMay the horse be with you\nMay the horse be with you\nIn every gallop, every stride\nMay the horse be with you\n\n[End]",
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: [
        {
          id: '8f2fbeeb-626b-4d15-93ae-e3e993aae1a6',
          continue_at: 102.4,
        },
        {
          id: '62e9a150-c8d4-4d0f-a192-de69094d7faa',
          continue_at: null,
        },
      ],
      type: 'concat',
      duration: 114.95997916666667,
      refund_credits: null,
      stream: null,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: 'f959f758-561d-4aa6-9c56-680ef3b03b15',
      play_count: 3,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-04T20:30:28.441Z',
    },
    created_at: '2024-04-04T20:29:47.954Z',
    status: 'complete',
    title: 'May the horse be with you',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '62e9a150-c8d4-4d0f-a192-de69094d7faa',
    video_url: 'https://cdn1.suno.ai/62e9a150-c8d4-4d0f-a192-de69094d7faa.mp4',
    audio_url: 'https://cdn1.suno.ai/62e9a150-c8d4-4d0f-a192-de69094d7faa.mp3',
    image_url: 'https://cdn1.suno.ai/image_62e9a150-c8d4-4d0f-a192-de69094d7faa.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_62e9a150-c8d4-4d0f-a192-de69094d7faa.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'uplifting bluegrass',
      prompt: '[End]',
      gpt_description_prompt: null,
      audio_prompt_id: '8f2fbeeb-626b-4d15-93ae-e3e993aae1a6',
      history: [
        {
          id: '8f2fbeeb-626b-4d15-93ae-e3e993aae1a6',
          continue_at: 102.4,
        },
      ],
      concat_history: null,
      type: 'gen',
      duration: 12.56,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '62e9a150-c8d4-4d0f-a192-de69094d7faa',
      play_count: 1,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-04T20:29:30.451Z',
    },
    created_at: '2024-04-04T20:28:28.497Z',
    status: 'complete',
    title: 'May the horse be with you',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '0ab7c73e-7d1e-40c6-a415-379e3c402b4a',
    video_url: 'https://cdn1.suno.ai/0ab7c73e-7d1e-40c6-a415-379e3c402b4a.mp4',
    audio_url: 'https://cdn1.suno.ai/0ab7c73e-7d1e-40c6-a415-379e3c402b4a.mp3',
    image_url: 'https://cdn1.suno.ai/image_0ab7c73e-7d1e-40c6-a415-379e3c402b4a.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_0ab7c73e-7d1e-40c6-a415-379e3c402b4a.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'uplifting bluegrass',
      prompt: '[End]',
      gpt_description_prompt: null,
      audio_prompt_id: '8f2fbeeb-626b-4d15-93ae-e3e993aae1a6',
      history: [
        {
          id: '8f2fbeeb-626b-4d15-93ae-e3e993aae1a6',
          continue_at: 102.4,
        },
      ],
      concat_history: null,
      type: 'gen',
      duration: 11.2,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '0ab7c73e-7d1e-40c6-a415-379e3c402b4a',
      play_count: 2,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-04T20:29:21.458Z',
    },
    created_at: '2024-04-04T20:28:28.497Z',
    status: 'complete',
    title: 'May the horse be with you',
    play_count: 9,
    upvote_count: 0,
    is_public: false,
  },
  {
    id: '09a6ef9b-b56b-4933-b0c1-209218dd177b',
    video_url: 'https://cdn1.suno.ai/09a6ef9b-b56b-4933-b0c1-209218dd177b.mp4',
    audio_url: 'https://cdn1.suno.ai/09a6ef9b-b56b-4933-b0c1-209218dd177b.mp3',
    image_url: 'https://cdn1.suno.ai/image_09a6ef9b-b56b-4933-b0c1-209218dd177b.png',
    image_large_url: 'https://cdn1.suno.ai/image_large_09a6ef9b-b56b-4933-b0c1-209218dd177b.png',
    is_video_pending: false,
    major_model_version: 'v3',
    model_name: 'chirp-v3',
    metadata: {
      tags: 'uplifting bluegrass',
      prompt:
        "[Verse 1]\nIn fields where wild winds dance and play,\nWhere sunbeams paint the dawning day,\nThere strides a friend, both swift and true,\nAcross the fields, beneath skies so blue,\n\n[Pre-chorus]\nWith mane that flows like rivers free,\nAnd eyes that hold eternity,\nEach hoofbeat echoes tales untold,\nOf journeys vast and dreams unfold.\n\n[Chorus]\nMay the horse be with you\nMay the horse be with you\nIn every gallop, every stride\nMay the horse be with you\n\n[Verse 2]\nThrough meadows green and valleys deep,\nWith May, the horse, there's naught to keep,\nBut soaring hearts and spirits bright,\nGuided by the stars at night.\n\n[Pre-chorus]\nWith mane that flows like rivers free,\nAnd eyes that hold eternity,\nEach hoofbeat echoes tales untold,\nOf journeys vast and dreams unfold.\n\n[Chorus]\nMay the horse be with you\nMay the horse be with you\nIn every gallop, every stride\nMay the horse be with you",
      gpt_description_prompt: null,
      audio_prompt_id: null,
      history: null,
      concat_history: null,
      type: 'gen',
      duration: 106.4,
      refund_credits: false,
      stream: true,
      error_type: null,
      error_message: null,
    },
    is_liked: true,
    user_id: '23b5ced5-81d0-450f-9512-5eb0d24562c4',
    display_name: 'jontonsoup',
    handle: 'jontonsoup',
    is_handle_updated: true,
    is_trashed: false,
    reaction: {
      clip: '09a6ef9b-b56b-4933-b0c1-209218dd177b',
      play_count: 3,
      skip_count: 0,
      flagged: false,
      flagged_reason: null,
      reaction_type: null,
      updated_at: '2024-04-04T20:28:18.670Z',
    },
    created_at: '2024-04-04T20:21:30.442Z',
    status: 'complete',
    title: 'May the horse be with you',
    play_count: 0,
    upvote_count: 0,
    is_public: false,
  },
];
